version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs/
      - ./data.db:/app/data.db
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "3005:80"
    depends_on:
      - backend
