name: backend
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - flask==1.1.4
    - flask-jwt-extended==3.25.0
    - flask-restful==0.3.9
    - flask-sqlalchemy==2.5.1
    - jinja2==2.11.3
    - pyjwt==1.7.1
    - python-dotenv==0.20.0
    - sqlalchemy==1.4.37
    - werkzeug==1.0.1
    - flask-cors==3.0.10
    - markupsafe==2.0.1
    - gunicorn
    - uuid